(package-initialize)
(add-to-list 'load-path "~/.emacs.d/aksarkar")
(add-to-list 'load-path "~/.emacs.d/vendor/")
(let ((default-directory "~/.emacs.d/vendor/"))
  (normal-top-level-add-subdirs-to-load-path))

(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("marmalade" . "http://marmalade-repo.org/packages/")
                         ("melpa" . "http://melpa.org/packages/")))

(require 'aksarkar-browse)
(require 'aksarkar-elfeed)
(require 'aksarkar-eshell)
(require 'aksarkar-avy)
(require 'aksarkar-git)
(require 'aksarkar-gui)
(require 'aksarkar-haskell)
(require 'aksarkar-helm)
(require 'aksarkar-ibuffer)
(require 'aksarkar-ispell)
(require 'aksarkar-keyboard)
(require 'aksarkar-mu4e)
(require 'aksarkar-org)
(require 'aksarkar-rcirc)
(require 'aksarkar-tex)
