(require 'elfeed)

(setq elfeed-feeds
      '(
        "http://blog.shakirm.com/feed/"
        "http://carlos.bueno.org/atom.xml"
        "http://unremediatedgender.space/feeds/all.atom.xml"
        "http://wavefunction.fieldofscience.com/feeds/posts/default"
        "http://www.ashokkarra.com/feed/"
        "http://www.randomprogramming.com/feed/"
        "https://aella.substack.com/feed/"
        "https://alexdanco.com/feed/"
        "https://annagat.substack.com/feed"
        "https://apenwarr.ca/log/rss.php"
        "https://astralcodexten.substack.com/feed"
        "https://balioc.wordpress.com/feed/"
        "https://bbs.archlinux.org/extern.php?action=feed&tid=250765&type=atom"
        "https://blog.acolyer.org/feed/"
        "https://blog.aurynn.com/feed.rss"
        "https://blog.computationalcomplexity.org/feeds/posts/default"
        "https://blog.cryptographyengineering.com/feeds/posts/default"
        "https://blog.jaibot.com/feed/"
        "https://blog.samaltman.com/posts.atom"
        "https://commandcenter.blogspot.com/feeds/posts/default"
        "https://compmeta.wordpress.com/feed/"
        "https://dabeaz.blogspot.com/feeds/posts/default"
        "https://danwang.co/?feed=rss"
        "https://donsbot.wordpress.com/feed/"
        "https://eigenrobot.substack.com/feed/"
        "https://elliotth.blogspot.com/feeds/posts/default"
        "https://ericlippert.com/feed/"
        "https://everythingstudies.com/feed/"
        "https://evincarofautumn.blogspot.com/feeds/posts/default"
        "https://expandingawareness.org/blog/rss/"
        "https://feeds.feedburner.com/MeltingAsphalt"
        "https://geneticvariance.wordpress.com/feed/"
        "https://juliagalef.com/feed/"
        "https://jvns.ca/atom.xml"
        "https://knowingless.com/feed/"
        "https://matt.might.net/articles/feed.rss"
        "https://michaelnielsen.org/ddi/feed/"
        "https://neopythonic.blogspot.com/feeds/posts/default"
        "https://particularvirtue.blogspot.com/feeds/posts/default"
        "https://pressthink.org/feed/"
        "https://prog21.dadgum.com/atom.xml"
        "https://pseudoerasmus.com/feed/"
        "https://putanumonit.com/feed/"
        "https://radimentary.wordpress.com/feed/"
        "https://rogersbacon.substack.com/feed"
        "https://rss.art19.com/closer-than-they-appear"
        "https://samreuben.wordpress.com/feed/"
        "https://samzdat.com/feed/"
        "https://slatestarcodex.com/feed/"
        "https://srconstantin.wordpress.com/feed/"
        "https://status451.com/feed/"
        "https://swellandcut.com/feed/"
        "https://themonadreader.wordpress.com/feed/"
        "https://theunitofcaring.tumblr.com/rss"
        "https://thezvi.wordpress.com/feed/"
        "https://thingsthatchangethewayithink.blogspot.com/feeds/posts/default"
        "https://unstableontology.com/feed/"
        "https://write.as/harold-lee/feed/"
        "https://www.adamjuliangoldstein.com/feed.xml"
        "https://www.alexirpan.com/feed.xml"
        "https://www.archlinux.org/feeds/news/"
        "https://www.cs.uni.edu/~wallingf/blog/index.xml"
        "https://www.ethanzuckerman.com/blog/feed/"
        "https://www.inference.vc/rss/"
        "https://www.megatokyo.com/rss/megatokyo.xml"
        "https://www.nxn.se/valent?format=RSS"
        "https://www.otherlife.co/blog/rss/"
        "https://www.quinnnorton.com/said/?feed=rss2"
        "https://www.scottaaronson.blog/?feed=rss2"
        "https://www.sonyasupposedly.com/rss/"
        "https://www.thinkthelimit.com/rss/"
        "https://zmagg.tumblr.com/rss"
        )
      elfeed-search-clipboard-type 'CLIPBOARD
      elfeed-search-filter "+unread"
      url-queue-timeout 30)

(provide 'aksarkar-elfeed)
